# Workflow to trigger a manual rebuild of my personal site when the theme changes

name: Page Rebuild

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  page-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Request Page Rebuild
      run: curl --header "Authorization:\ {{ secrets.PAT }}" --request POST https://api.github.com/repos/bartlettD/bartlettD.github.io/pages/builds
