# Workflow to trigger a manual rebuild of my personal site when the theme changes

name: Page Rebuild

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  page-build:
    runs-on: ubuntu-latest

    steps:
    # Send a POST to the pages API to request a rebuild.
    - name: Request Page Rebuild
      run: |
        curl --request POST \
        --header 'Authorization: token {{ secrets.PAT }}'  \
        https://api.github.com/repos/bartlettD/bartlettD.github.io/pages/builds
